#!/usr/bin/env python
# vim: ai ts=4 sts=4 et sw=4



import rapidsms
import re
import MySQLdb

from rapidsms.apps.base import AppBase
from models import *
from datetime import datetime
from django.db import connection, transaction

class App (AppBase):
    def start (self):
        """Configure your app in the start phase."""
        pass

    def parse (self, message):
        """Parse and annotate messages in the parse phase."""
        pass
    
    def handle (self, message):
        self.debug("got message %s", message.text)
        db1=MySQLdb.connect (host = "localhost", user = "root",passwd = "romo",db = "mydb")
        cursor = db1.cursor()
        t = message.text
        t1= t.upper()
        t2= t1.strip()
        r = t2.split(',')
        if r[1] == 'W':  
            if r[5] == 'Q':  
                d1 = datetime.strptime(r[7],'%Y-%m-%d')
                tab1 = warehouse(warehouse_smsType=r[0],warehouse_state_id=int(r[2]),warehouse_quality=int(r[6]),warehouse_ArvTime=d1)
                tab1.save()
                cursor.execute("SELECT MAX(warehouse_MsgID) from SKD_app_warehouse")
                d2 = cursor.fetchone() 
                tab2 = warehouseTypes(warehouseTypes_Type=r[3],warehouseTypes_quantity=int(r[4]),warehouseTypes_msgId_id=int(d2[0]))
                tab2.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[7] == 'Q':  
                d1 = datetime.strptime(r[9],'%Y-%m-%d')
                tab1 = warehouse(warehouse_smsType=r[0],warehouse_state_id=int(r[2]),warehouse_ArvTime=d1,warehouse_quality=int(r[8]))
                tab1.save()
                cursor.execute("SELECT MAX(warehouse_MsgID) from SKD_app_warehouse")
                d2 = cursor.fetchone()
                tab2 = warehouseTypes(warehouseTypes_Type=r[3],warehouseTypes_quantity=int(r[4]),warehouseTypes_msgId_id=int(d2[0]))
                tab3 = warehouseTypes(warehouseTypes_Type=r[5],warehouseTypes_quantity=int(r[6]),warehouseTypes_msgId_id=int(d2[0]))
                tab2.save()
                tab3.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[9] == 'Q':  
                d1 = datetime.strptime(r[11],'%Y-%m-%d')
                tab1 = warehouse(warehouse_smsType=r[0],warehouse_state_id=int(r[2]),warehouse_ArvTime=d1,warehouse_quality=int(r[10]))
                tab1.save()
                cursor.execute("SELECT MAX(warehouse_MsgID) from SKD_app_warehouse")
                d2 = cursor.fetchone()
                tab2 = warehouseTypes(warehouseTypes_Type=r[3],warehouseTypes_quantity=int(r[4]),warehouseTypes_msgId_id=int(d2[0]))
                tab3 = warehouseTypes(warehouseTypes_Type=r[5],warehouseTypes_quantity=int(r[6]),warehouseTypes_msgId_id=int(d2[0]))
                tab4 = warehouseTypes(warehouseTypes_Type=r[7],warehouseTypes_quantity=int(r[8]),warehouseTypes_msgId_id=int(d2  [0]))               
                tab2.save()
                tab3.save()
                tab4.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[11] == 'Q':
                d1 = datetime.strptime(r[13],'%Y-%m-%d')
                tab1 = warehouse(warehouse_smsType=r[0],warehouse_state_id=int(r[2]),warehouse_ArvTime=d1,warehouse_quality=int(r[12]))
                tab1.save()
                cursor.execute("SELECT MAX(warehouse_MsgID) from SKD_app_warehouse")
                d2 = cursor.fetchone()
                tab2 = warehouseTypes(warehouseTypes_Type=r[3],warehouseTypes_quantity=int(r[4]),warehouseTypes_msgId_id=int(d2[0]))
                tab3 = warehouseTypes(warehouseTypes_Type=r[5],warehouseTypes_quantity=int(r[6]),warehouseTypes_msgId_id=int(d2[0]))
                tab4 = warehouseTypes(warehouseTypes_Type=r[7],warehouseTypes_quantity=int(r[8]),warehouseTypes_msgId_id=int(d2[0]))
                tab5 = warehouseTypes(warehouseTypes_Type=r[9],warehouseTypes_quantity=int(r[10]),warehouseTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[13] == 'Q':    
                d1 = datetime.strptime(r[15],'%Y-%m-%d')
                tab1 = warehouse(warehouse_smsType=r[0],warehouse_state_id=int(r[2]),warehouse_ArvTime=d1,warehouse_quality=int(r[14]))
                tab1.save()
                cursor.execute("SELECT MAX(warehouse_MsgID) from SKD_app_warehouse")
                d2 = cursor.fetchone()
                tab2 = warehouseTypes(warehouseTypes_Type=r[3],warehouseTypes_quantity=int(r[4]),warehouseTypes_msgId_id=int(d2[0]))
                tab3 = warehouseTypes(warehouseTypes_Type=r[5],warehouseTypes_quantity=int(r[6]),warehouseTypes_msgId_id=int(d2[0]))
                tab4 = warehouseTypes(warehouseTypes_Type=r[7],warehouseTypes_quantity=int(r[8]),warehouseTypes_msgId_id=int(d2[0]))
                tab5 = warehouseTypes(warehouseTypes_Type=r[9],warehouseTypes_quantity=int(r[10]),warehouseTypes_msgId_id=int(d2[0]))
                tab6 = warehouseTypes(warehouseTypes_Type=r[11],warehouseTypes_quantity=int(r[12]),warehouseTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True         
            elif r[15] == 'Q':    
                d1 = datetime.strptime(r[17],'%Y-%m-%d')
                tab1 = warehouse(warehouse_smsType=r[0],warehouse_state_id=int(r[2]),warehouse_ArvTime=d1,warehouse_quality=int(r[16]))
                tab1.save()
                cursor.execute("SELECT MAX(warehouse_MsgID) from SKD_app_warehouse")
                d2 = cursor.fetchone()
                tab2 = warehouseTypes(warehouseTypes_Type=r[3],warehouseTypes_quantity=int(r[4]),warehouseTypes_msgId_id=int(d2[0]))
                tab3 = warehouseTypes(warehouseTypes_Type=r[5],warehouseTypes_quantity=int(r[6]),warehouseTypes_msgId_id=int(d2[0]))
                tab4 = warehouseTypes(warehouseTypes_Type=r[7],warehouseTypes_quantity=int(r[8]),warehouseTypes_msgId_id=int(d2[0]))
                tab5 = warehouseTypes(warehouseTypes_Type=r[9],warehouseTypes_quantity=int(r[10]),warehouseTypes_msgId_id=int(d2[0]))
                tab6 = warehouseTypes(warehouseTypes_Type=r[11],warehouseTypes_quantity=int(r[12]),warehouseTypes_msgId_id=int(d2[0]))
                tab7 = warehouseTypes(warehouseTypes_Type=r[13],warehouseTypes_quantity=int(r[14]),warehouseTypes_msgId_id=int(d2[0]))               
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True    
            elif r[17] == 'Q':    
                d1 = datetime.strptime(r[19],'%Y-%m-%d')
                tab1 = warehouse(warehouse_smsType=r[0],warehouse_state_id=int(r[2]),warehouse_ArvTime=d1,warehouse_quality=int(r[18]))
                tab1.save()
                cursor.execute("SELECT MAX(warehouse_MsgID) from SKD_app_warehouse")
                d2 = cursor.fetchone()
                tab2 = warehouseTypes(warehouseTypes_Type=r[3],warehouseTypes_quantity=int(r[4]),warehouseTypes_msgId_id=int(d2[0]))
                tab3 = warehouseTypes(warehouseTypes_Type=r[5],warehouseTypes_quantity=int(r[6]),warehouseTypes_msgId_id=int(d2[0]))
                tab4 = warehouseTypes(warehouseTypes_Type=r[7],warehouseTypes_quantity=int(r[8]),warehouseTypes_msgId_id=int(d2[0]))
                tab5 = warehouseTypes(warehouseTypes_Type=r[9],warehouseTypes_quantity=int(r[10]),warehouseTypes_msgId_id=int(d2[0]))
                tab6 = warehouseTypes(warehouseTypes_Type=r[11],warehouseTypes_quantity=int(r[12]),warehouseTypes_msgId_id=int(d2[0]))
                tab7 = warehouseTypes(warehouseTypes_Type=r[13],warehouseTypes_quantity=int(r[14]),warehouseTypes_msgId_id=int(d2[0]))
                tab8 = warehouseTypes(warehouseTypes_Type=r[15],warehouseTypes_quantity=int(r[16]),warehouseTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True  
            elif r[19] == 'Q':    
                d1 = datetime.strptime(r[21],'%Y-%m-%d')
                tab1 = warehouse(warehouse_smsType=r[0],warehouse_state_id=int(r[2]),warehouse_ArvTime=d1,warehouse_quality=int(r[20]))
                tab1.save()
                cursor.execute("SELECT MAX(warehouse_MsgID) from SKD_app_warehouse")
                d2 = cursor.fetchone()
                tab2 = warehouseTypes(warehouseTypes_Type=r[3],warehouseTypes_quantity=int(r[4]),warehouseTypes_msgId_id=int(d2[0]))
                tab3 = warehouseTypes(warehouseTypes_Type=r[5],warehouseTypes_quantity=int(r[6]),warehouseTypes_msgId_id=int(d2[0]))
                tab4 = warehouseTypes(warehouseTypes_Type=r[7],warehouseTypes_quantity=int(r[8]),warehouseTypes_msgId_id=int(d2[0]))
                tab5 = warehouseTypes(warehouseTypes_=r[9],warehouseTypes_quantity=int(r[10]),warehouseTypes_msgId_id=int(d2[0]))
                tab6 = warehouseTypes(warehouseTypes_Type=r[11],warehouseTypes_quantity=int(r[12]),warehouseTypes_msgId_id=int(d2[0]))
                tab7 = warehouseTypes(warehouseTypes_Type=r[13],warehouseTypes_quantity=int(r[14]),warehouseTypes_msgId_id=int(d2[0]))
                tab8 = warehouseTypes(warehouseTypes_Type=r[15],warehouseTypes_quantity=int(r[16]),warehouseTypes_msgId_id=int(d2[0]))
                tab9 = warehouseTypes(warehouseTypes_Type=r[16],warehouseTypes_quantity=int(r[17]),warehouseTypes_msgId_id=int(d2[0]))               
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True         
            elif r[21] == 'Q':    
                d1 = datetime.strptime(r[23],'%Y-%m-%d')
                tab1 = warehouse(warehouse_smsType=r[0],warehouse_state_id=int(r[2]),warehouse_ArvTime=d1,warehouse_quality=int(r[22]))
                tab1.save()
                cursor.execute("SELECT MAX(warehouse_MsgID) from SKD_app_warehouse")
                d2 = cursor.fetchone()
                tab2 = warehouseTypes(warehouseTypes_Type=r[3],warehouseTypes_quantity=int(r[4]),warehouseTypes_msgId_id=int(d2[0]))
                tab3 = warehouseTypes(warehouseTypes_Type=r[5],warehouseTypes_quantity=int(r[6]),warehouseTypes_msgId_id=int(d2[0]))
                tab4 = warehouseTypes(warehouseTypes_Type=r[7],warehouseTypes_quantity=int(r[8]),warehouseTypes_msgId_id=int(d2[0]))
                tab5 = warehouseTypes(warehouseTypes_Type=r[9],warehouseTypes_quantity=int(r[10]),warehouseTypes_msgId_id=int(d2[0]))
                tab6 = warehouseTypes(warehouseTypes_Type=r[11],warehouseTypes_quantity=int(r[12]),warehouseTypes_msgId_id=int(d2[0]))
                tab7 = warehouseTypes(warehouseTypes_Type=r[13],warehouseTypes_quantity=int(r[14]),warehouseTypes_msgId_id=int(d2[0]))
                tab8 = warehouseTypes(warehouseTypes_Type=r[15],warehouseTypes_quantity=int(r[16]),warehouseTypes_msgId_id=int(d2[0]))
                tab9 = warehouseTypes(warehouseTypes_Type=r[16],warehouseTypes_quantity=int(r[17]),warehouseTypes_msgId_id=int(d2[0]))
                tab10 = warehouseTypes(warehouseTypes_Type=r[18],warehouseTypes_quantity=int(r[19]),warehouseTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True     
            elif r[23] == 'Q':    
                d1 = datetime.strptime(r[25],'%Y-%m-%d')
                tab1 = warehouse(warehouse_smsType=r[0],warehouse_state_id=int(r[2]),warehouse_ArvTime=d1,warehouse_quality=int(r[24]))
                tab1.save()
                cursor.execute("SELECT MAX(warehouse_MsgID) from SKD_app_warehouse")
                d2 = cursor.fetchone()
                tab2 = warehouseTypes(warehouseTypes_Type=r[3],warehouseTypes_quantity=int(r[4]),warehouseTypes_msgId_id=int(d2[0]))
                tab3 = warehouseTypes(warehouseTypes_Type=r[5],warehouseTypes_quantity=int(r[6]),warehouseTypes_msgId_id=int(d2[0]))
                tab4 = warehouseTypes(warehouseTypes_Type=r[7],warehouseTypes_quantity=int(r[8]),warehouseTypes_msgId_id=int(d2[0]))
                tab5 = warehouseTypes(warehouseTypes_Type=r[9],warehouseTypes_quantity=int(r[10]),warehouseTypes_msgId_id=int(d2[0]))
                tab6 = warehouseTypes(warehouseTypes_Type=r[11],warehouseTypes_quantity=int(r[12]),warehouseTypes_msgId_id=int(d2[0]))
                tab7 = warehouseTypes(warehouseTypes_Type=r[13],warehouseTypes_quantity=int(r[14]),warehouseTypes_msgId_id=int(d2[0]))
                tab8 = warehouseTypes(warehouseTypes_Type=r[15],warehouseTypes_quantity=int(r[16]),warehouseTypes_msgId_id=int(d2[0]))
                tab9 = warehouseTypes(warehouseTypes_Type=r[16],warehouseTypes_quantity=int(r[17]),warehouseTypes_msgId_id=int(d2[0]))
                tab10 = warehouseTypes(warehouseTypes_Type=r[18],warehouseTypes_quantity=int(r[19]),warehouseTypes_msgId_id=int(d2[0]))
                tab11 = warehouseTypes(warehouseTypes_Type=r[21],warehouseTypes_quantity=int(r[22]),warehouseTypes_msgId_id=int(d2[0]))               
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                tab11.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True     
            elif r[25] == 'Q':    
                d1 = datetime.strptime(r[27],'%Y-%m-%d')
                tab1 = warehouse(warehouse_smsType=r[0],warehouse_state_id=int(r[2]),warehouse_ArvTime=d1,warehouse_quality=int(r[26]))
                tab1.save()
                cursor.execute("SELECT MAX(warehouse_MsgID) from SKD_app_warehouse")
                d2 = cursor.fetchone()
                tab2 = warehouseTypes(warehouseTypes_Type=r[3],warehouseTypes_quantity=int(r[4]),warehouseTypes_msgId_id=int(d2[0]))
                tab3 = warehouseTypes(warehouseTypes_Type=r[5],warehouseTypes_quantity=int(r[6]),warehouseTypes_msgId_id=int(d2[0]))
                tab4 = warehouseTypes(warehouseTypes_Type=r[7],warehouseTypes_quantity=int(r[8]),warehouseTypes_msgId_id=int(d2[0]))
                tab5 = warehouseTypes(warehouseTypes_Type=r[9],warehouseTypes_quantity=int(r[10]),warehouseTypes_msgId_id=int(d2[0]))
                tab6 = warehouseTypes(warehouseTypes_Type=r[11],warehouseTypes_quantity=int(r[12]),warehouseTypes_msgId_id=int(d2[0]))
                tab7 = warehouseTypes(warehouseTypes_Type=r[13],warehouseTypes_quantity=int(r[14]),warehouseTypes_msgId_id=int(d2[0]))
                tab8 = warehouseTypes(warehouseTypes_Type=r[15],warehouseTypes_quantity=int(r[16]),warehouseTypes_msgId_id=int(d2[0]))
                tab9 = warehouseTypes(warehouseTypes_Type=r[16],warehouseTypes_quantity=int(r[17]),warehouseTypes_msgId_id=int(d2[0]))
                tab10 = warehouseTypes(warehouseTypes_Type=r[18],warehouseTypes_quantity=int(r[19]),warehouseTypes_msgId_id=int(d2[0]))
                tab11 = warehouseTypes(warehouseTypes_Type=r[21],warehouseTypes_quantity=int(r[22]),warehouseTypes_msgId_id=int(d2[0]))
                tab12 = warehouseTypes(warehouseTypes_Type=r[23],warehouseTypes_quantity=int(r[24]),warehouseTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                tab11.save()   
                tab12.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True      
            elif r[27] == 'Q':    
                d1 = datetime.strptime(r[29],'%Y-%m-%d')
                tab1 = warehouse(warehouse_smsType=r[0],warehouse_state_id=int(r[2]),warehouse_ArvTime=d1,warehouse_quality=int(r[28]))
                tab1.save()
                cursor.execute("SELECT MAX(warehouse_MsgID) from SKD_app_warehouse")
                d2 = cursor.fetchone()
                tab2 = warehouseTypes(warehouseTypes_Type=r[3],warehouseTypes_quantity=int(r[4]),warehouseTypes_msgId_id=int(d2[0]))
                tab3 = warehouseTypes(warehouseTypes_Type=r[5],warehouseTypes_quantity=int(r[6]),warehouseTypes_msgId_id=int(d2[0]))
                tab4 = warehouseTypes(warehouseTypes_Type=r[7],warehouseTypes_quantity=int(r[8]),warehouseTypes_msgId_id=int(d2[0]))
                tab5 = warehouseTypes(warehouseTypes_Type=r[9],warehouseTypes_quantity=int(r[10]),warehouseTypes_msgId_id=int(d2[0]))
                tab6 = warehouseTypes(warehouseTypes_Type=r[11],warehouseTypes_quantity=int(r[12]),warehouseTypes_msgId_id=int(d2[0]))
                tab7 = warehouseTypes(warehouseTypes_Type=r[13],warehouseTypes_quantity=int(r[14]),warehouseTypes_msgId_id=int(d2[0]))
                tab8 = warehouseTypes(warehouseTypes_Type=r[15],warehouseTypes_quantity=int(r[16]),warehouseTypes_msgId_id=int(d2[0]))
                tab9 = warehouseTypes(warehouseTypes_Type=r[16],warehouseTypes_quantity=int(r[17]),warehouseTypes_msgId_id=int(d2[0]))
                tab10 = warehouseTypes(warehouseTypes_Type=r[18],warehouseTypes_quantity=int(r[19]),warehouseTypes_msgId_id=int(d2[0]))
                tab11 = warehouseTypes(warehouseTypes_Type=r[21],warehouseTypes_quantity=int(r[22]),warehouseTypes_msgId_id=int(d2[0]))
                tab12 = warehouseTypes(warehouseTypes_Type=r[23],warehouseTypes_quantity=int(r[24]),warehouseTypes_msgId_id=int(d2[0]))
                tab13 = warehouseTypes(warehouseTypes_Type=r[25],warehouseTypes_quantity=int(r[26]),warehouseTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                tab11.save()   
                tab12.save()
                tab13.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True 
        elif r[1] == 'M':
            if r[6] == 'Q':
                d1 = datetime.strptime(r[8],'%Y-%m-%d')
                tab1 = state(state_smsType=r[0],state_state_id=int(r[2]),state_locality_id=int(r[3]),state_ArvTime=d1,state_quality=int(r[7])) 
                tab1.save()
                cursor.execute("SELECT MAX(state_MsgID) from SKD_app_state")
                d2 = cursor.fetchone()
                tab2 = stateTypes(stateTypes_Type=r[4],stateTypes_quantity=int(r[5]),stateTypes_msgId_id=int(d2[0]))                
                tab2.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True  
            elif r[8] == 'Q':  
                d1 = datetime.strptime(r[10],'%Y-%m-%d')
                tab1 = state(state_smsType=r[0],state_state_id=int(r[2]),state_locality_id=int(r[3]),state_ArvTime=d1,state_quality=int(r[9])) 
                tab1.save()
                cursor.execute("SELECT MAX(state_MsgID) from SKD_app_state")
                d2 = cursor.fetchone()
                tab2 = stateTypes(stateTypes_Type=r[4],stateTypes_quantity=int(r[5]),stateTypes_msgId_id=int(d2[0]))
                tab3 = stateTypes(stateTypes_Type=r[6],stateTypes_quantity=int(r[7]),stateTypes_msgId_id=int(d2[0]))               
                tab2.save()
                tab3.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[10] == 'Q':  
                d1 = datetime.strptime(r[12],'%Y-%m-%d')
                tab1 = state(state_smsType=r[0],state_state_id=int(r[2]),state_locality_id=int(r[3]),state_ArvTime=d1,state_quality=int(r[11]))
                tab1.save()
                cursor.execute("SELECT MAX(state_MsgID) from SKD_app_state")
                d2 = cursor.fetchone() 
                tab2 = stateTypes(stateTypes_Type=r[4],stateTypes_quantity=int(r[5]),stateTypes_msgId_id=int(d2[0]))
                tab3 = stateTypes(stateTypes_Type=r[6],stateTypes_quantity=int(r[7]),stateTypes_msgId_id=int(d2[0]))
                tab4 = stateTypes(stateTypes_Type=r[8],stateTypes_quantity=int(r[9]),stateTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[12] == 'Q':    
                d1 = datetime.strptime(r[14],'%Y-%m-%d')
                tab1 = state(state_smsType=r[0],state_state_id=int(r[2]),state_locality_id=int(r[3]),state_ArvTime=d1,state_quality=int(r[13]))
                tab1.save() 
                cursor.execute("SELECT MAX(state_MsgID) from SKD_app_state")
                d2 = cursor.fetchone()
                tab2 = stateTypes(stateTypes_Type=r[4],stateTypes_quantity=int(r[5]),stateTypes_msgId_id=int(d2[0]))
                tab3 = stateTypes(stateTypes_Type=r[6],stateTypes_quantity=int(r[7]),stateTypes_msgId_id=int(d2[0]))
                tab4 = stateTypes(stateTypes_Type=r[8],stateTypes_quantity=int(r[9]),stateTypes_msgId_id=int(d2[0]))
                tab5 = stateTypes(stateTypes_Type=r[10],stateTypes_quantity=int(r[11]),stateTypes_msgId_id=int(d2[0]))               
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[14] == 'Q':    
                d1 = datetime.strptime(r[16],'%Y-%m-%d')
                tab1 = state(state_smsType=r[0],state_state_id=int(r[2]),state_locality_id=int(r[3]),state_ArvTime=d1,state_quality=int(r[15]))
                tab1.save() 
                cursor.execute("SELECT MAX(state_MsgID) from SKD_app_state")
                d2 = cursor.fetchone()
                tab2 = stateTypes(stateTypes_Type=r[4],stateTypes_quantity=int(r[5]),stateTypes_msgId_id=int(d2[0]))
                tab3 = stateTypes(stateTypes_Type=r[6],stateTypes_quantity=int(r[7]),stateTypes_msgId_id=int(d2[0]))
                tab4 = stateTypes(stateTypes_Type=r[8],stateTypes_quantity=int(r[9]),stateTypes_msgId_id=int(d2[0]))
                tab5 = stateTypes(stateTypes_Type=r[10],stateTypes_quantity=int(r[11]),stateTypes_msgId_id=int(d2[0]))
                tab6 = stateTypes(stateTypes_Type=r[12],stateTypes_quantity=int(r[13]),stateTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True         
            elif r[16] == 'Q':    
                d1 = datetime.strptime(r[18],'%Y-%m-%d')
                tab1 = state(state_smsType=r[0],state_state_id=int(r[2]),state_locality_id=int(r[3]),state_ArvTime=d1,state_quality=int(r[17])) 
                tab1.save()
                cursor.execute("SELECT MAX(state_MsgID) from SKD_app_state")
                d2 = cursor.fetchone()
                tab2 = stateTypes(stateTypes_Type=r[4],stateTypes_quantity=int(r[5]),stateTypes_msgId_id=int(d2[0]))
                tab3 = stateTypes(stateTypes_Type=r[6],stateTypes_quantity=int(r[7]),stateTypes_msgId_id=int(d2[0]))
                tab4 = stateTypes(stateTypes_Type=r[8],stateTypes_quantity=int(r[9]),stateTypes_msgId_id=int(d2[0]))
                tab5 = stateTypes(stateTypes_Type=r[10],stateTypes_quantity=int(r[11]),stateTypes_msgId_id=int(d2[0]))
                tab6 = stateTypes(stateTypes_Type=r[12],stateTypes_quantity=int(r[13]),stateTypes_msgId_id=int(d2[0]))
                tab7 = stateTypes(stateTypes_Type=r[14],stateTypes_quantity=int(r[15]),stateTypes_msgId_id=int(d2[0]))               
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()  
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True  
            elif r[18] == 'Q':    
                d1 = datetime.strptime(r[20],'%Y-%m-%d')
                tab1 = state(state_smsType=r[0],state_state_id=int(r[2]),state_locality_id=int(r[3]),state_ArvTime=d1,state_quality=int(r[19])) 
                tab1.save()
                cursor.execute("SELECT MAX(state_MsgID) from SKD_app_state")
                d2 = cursor.fetchone()
                tab2 = stateTypes(stateTypes_Type=r[4],stateTypes_quantity=int(r[5]),stateTypes_msgId_id=int(d2[0]))
                tab3 = stateTypes(stateTypes_Type=r[6],stateTypes_quantity=int(r[7]),stateTypes_msgId_id=int(d2[0]))
                tab4 = stateTypes(stateTypes_Type=r[8],stateTypes_quantity=int(r[9]),stateTypes_msgId_id=int(d2[0]))
                tab5 = stateTypes(stateTypes_Type=r[10],stateTypes_quantity=int(r[11]),stateTypes_msgId_id=int(d2[0]))
                tab6 = stateTypes(stateTypes_Type=r[12],stateTypes_quantity=int(r[13]),stateTypes_msgId_id=int(d2[0]))
                tab7 = stateTypes(Type=r[14],quantity=int(r[15]),msgId_id=int(d2[0]))
                tab8 = stateTypes(Type=r[16],quantity=int(r[17]),msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True 
            elif r[20] == 'Q':    
                d1 = datetime.strptime(r[22],'%Y-%m-%d')
                tab1 = state(state_smsType=r[0],state_state_id=int(r[2]),state_locality_id=int(r[3]),state_ArvTime=d1,state_quality=int(r[21]))
                tab1.save()
                cursor.execute("SELECT MAX(state_MsgID) from SKD_app_state")
                d2 = cursor.fetchone() 
                tab2 = stateTypes(stateTypes_Type=r[4],stateTypes_quantity=int(r[5]),stateTypes_msgId_id=int(d2[0]))
                tab3 = stateTypes(stateTypes_Type=r[6],stateTypes_quantity=int(r[7]),stateTypes_msgId_id=int(d2[0]))
                tab4 = stateTypes(stateTypes_Type=r[8],stateTypes_quantity=int(r[9]),stateTypes_msgId_id=int(d2[0]))
                tab5 = stateTypes(stateTypes_Type=r[10],stateTypes_quantity=int(r[11]),stateTypes_msgId_id=int(d2[0]))
                tab6 = stateTypes(stateTypes_Type=r[12],stateTypes_quantity=int(r[13]),stateTypes_msgId_id=int(d2[0]))
                tab7 = stateTypes(stateTypes_Type=r[14],stateTypes_quantity=int(r[15]),stateTypes_msgId_id=int(d2[0]))
                tab8 = stateTypes(stateTypes_Type=r[16],stateTypes_quantity=int(r[17]),stateTypes_msgId_id=int(d2[0]))
                tab9 = stateTypes(stateTypes_Type=r[18],stateTypes_quantity=int(r[19]),stateTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save()   
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True      
            elif r[22] == 'Q':    
                d1 = datetime.strptime(r[24],'%Y-%m-%d')
                tab1 = state(state_smsType=r[0],state_state_id=int(r[2]),state_locality_id=int(r[3]),state_ArvTime=d1,state_quality=int(r[23]))
                tab1.save()
                cursor.execute("SELECT MAX(state_MsgID) from SKD_app_state")
                d2 = cursor.fetchone() 
                tab2 = stateTypes(stateTypes_Type=r[4],stateTypes_quantity=int(r[5]),stateTypes_msgId_id=int(d2[0]))
                tab3 = stateTypes(stateTypes_Type=r[6],stateTypes_quantity=int(r[7]),stateTypes_msgId_id=int(d2[0]))
                tab4 = stateTypes(stateTypes_Type=r[8],stateTypes_quantity=int(r[9]),stateTypes_msgId_id=int(d2[0]))
                tab5 = stateTypes(stateTypes_Type=r[10],stateTypes_quantity=int(r[11]),stateTypes_msgId_id=int(d2[0]))
                tab6 = stateTypes(stateTypes_Type=r[12],stateTypes_quantity=int(r[13]),stateTypes_msgId_id=int(d2[0]))
                tab7 = stateTypes(stateTypes_Type=r[14],stateTypes_quantity=int(r[15]),stateTypes_msgId_id=int(d2[0]))
                tab8 = stateTypes(stateTypes_Type=r[16],stateTypes_quantity=int(r[17]),stateTypes_msgId_id=int(d2[0]))
                tab9 = stateTypes(stateTypes_Type=r[18],stateTypes_quantity=int(r[19]),stateTypes_msgId_id=int(d2[0]))
                tab10 = stateTypes(stateTypes_Type=r[20],stateTypes_quantity=int(r[21]),stateTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True     
            elif r[24] == 'Q':    
                d1 = datetime.strptime(r[26],'%Y-%m-%d')
                tab1 = state(state_smsType=r[0],state_state_id=int(r[2]),state_locality_id=int(r[3]),state_ArvTime=d1,state_quality=int(r[25]))
                tab1.save()
                cursor.execute("SELECT MAX(state_MsgID) from SKD_app_state")
                d2 = cursor.fetchone() 
                tab2 = stateTypes(stateTypes_Type=r[4],stateTypes_quantity=int(r[5]),stateTypes_msgId_id=int(d2[0]))
                tab3 = stateTypes(stateTypes_Type=r[6],stateTypes_quantity=int(r[7]),stateTypes_msgId_id=int(d2[0]))
                tab4 = stateTypes(stateTypes_Type=r[8],stateTypes_quantity=int(r[9]),stateTypes_msgId_id=int(d2[0]))
                tab5 = stateTypes(stateTypes_Type=r[10],stateTypes_quantity=int(r[11]),stateTypes_msgId_id=int(d2[0]))
                tab6 = stateTypes(stateTypes_Type=r[12],stateTypes_quantity=int(r[13]),stateTypes_msgId_id=int(d2[0]))
                tab7 = stateTypes(stateTypes_Type=r[14],stateTypes_quantity=int(r[15]),stateTypes_msgId_id=int(d2[0]))
                tab8 = stateTypes(stateTypes_Type=r[16],stateTypes_quantity=int(r[17]),stateTypes_msgId_id=int(d2[0]))
                tab9 = stateTypes(stateTypes_Type=r[18],stateTypes_quantity=int(r[19]),stateTypes_msgId_id=int(d2[0]))
                tab10 = stateTypes(stateTypes_Type=r[20],stateTypes_quantity=int(r[21]),stateTypes_msgId_id=int(d2[0]))
                tab11 = stateTypes(stateTypes_Type=r[22],stateTypes_quantity=int(r[23]),stateTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                tab11.save()   
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True  
            elif r[26] == 'Q':    
                d1 = datetime.strptime(r[28],'%Y-%m-%d')
                tab1 = state(state_smsType=r[0],state_state_id=int(r[2]),state_locality_id=int(r[3]),state_ArvTime=d1,state_quality=int(r[27])) 
                tab1.save()
                cursor.execute("SELECT MAX(state_MsgID) from SKD_app_state")
                d2 = cursor.fetchone()
                tab2 = stateTypes(stateTypes_Type=r[4],stateTypes_quantity=int(r[5]),stateTypes_msgId_id=int(d2[0]))
                tab3 = stateTypes(stateTypes_Type=r[6],stateTypes_quantity=int(r[7]),stateTypes_msgId_id=int(d2[0]))
                tab4 = stateTypes(stateTypes_Type=r[8],stateTypes_quantity=int(r[9]),stateTypes_msgId_id=int(d2[0]))
                tab5 = stateTypes(stateTypes_Type=r[10],stateTypes_quantity=int(r[11]),stateTypes_msgId_id=int(d2[0]))
                tab6 = stateTypes(stateTypes_Type=r[12],stateTypes_quantity=int(r[13]),stateTypes_msgId_id=int(d2[0]))
                tab7 = stateTypes(stateTypes_Type=r[14],stateTypes_quantity=int(r[15]),stateTypes_msgId_id=int(d2[0]))
                tab8 = stateTypes(stateTypes_Type=r[16],stateTypes_quantity=int(r[17]),stateTypes_msgId_id=int(d2[0]))
                tab9 = stateTypes(stateTypes_Type=r[18],stateTypes_quantity=int(r[19]),stateTypes_msgId_id=int(d2[0]))
                tab10 = stateTypes(stateTypes_Type=r[20],stateTypes_quantity=int(r[21]),stateTypes_msgId_id=int(d2[0]))
                tab11 = stateTypes(stateTypes_Type=r[22],stateTypes_quantity=int(r[23]),stateTypes_msgId_id=int(d2[0]))
                tab12 = stateTypes(stateTypes_Type=r[24],stateTypes_quantity=int(r[25]),stateTypes_msgId_id=int(d2[0]))               
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                tab11.save()   
                tab12.save()  
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True    
            elif r[28] == 'Q':    
                d1 = datetime.strptime(r[30],'%Y-%m-%d')
                tab1 = state(state_smsType=r[0],state_state_id=int(r[2]),state_locality_id=int(r[3]),state_ArvTime=d1,state_quality=int(r[29])) 
                tab1.save()
                cursor.execute("SELECT MAX(state_MsgID) from SKD_app_state")
                d2 = cursor.fetchone()
                tab2 = stateTypes(stateTypes_Type=r[4],stateTypes_quantity=int(r[5]),stateTypes_msgId_id=int(d2[0]))
                tab3 = stateTypes(stateTypes_Type=r[6],stateTypes_quantity=int(r[7]),stateTypes_msgId_id=int(d2[0]))
                tab4 = stateTypes(stateTypes_Type=r[8],stateTypes_quantity=int(r[9]),stateTypes_msgId_id=int(d2[0]))
                tab5 = stateTypes(stateTypes_Type=r[10],stateTypes_quantity=int(r[11]),stateTypes_msgId_id=int(d2[0]))
                tab6 = stateTypes(stateTypes_Type=r[12],stateTypes_quantity=int(r[13]),stateTypes_msgId_id=int(d2[0]))
                tab7 = stateTypes(stateTypes_Type=r[14],stateTypes_quantity=int(r[15]),stateTypes_msgId_id=int(d2[0]))
                tab8 = stateTypes(stateTypes_Type=r[16],stateTypes_quantity=int(r[17]),stateTypes_msgId_id=int(d2[0]))
                tab9 = stateTypes(stateTypes_Type=r[18],stateTypes_quantity=int(r[19]),stateTypes_msgId_id=int(d2[0]))
                tab10 = stateTypes(stateTypes_Type=r[20],stateTypes_quantity=int(r[21]),stateTypes_msgId_id=int(d2[0]))
                tab11 = stateTypes(stateTypes_Type=r[22],stateTypes_quantity=int(r[23]),stateTypes_msgId_id=int(d2[0]))
                tab12 = stateTypes(stateTypes_Type=r[24],stateTypes_quantity=int(r[25]),stateTypes_msgId_id=int(d2[0]))
                tab13 = stateTypes(stateTypes_Type=r[26],stateTypes_quantity=int(r[27]),stateTypes_msgId_id=int(d2[0]))               
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                tab11.save()   
                tab12.save()
                tab13.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True                                                                     
        elif r[1] == 'L':  
            if r[7] == 'Q':
                d1 = datetime.strptime(r[9],'%Y-%m-%d')
                tab1 = locality(locality_smsType=r[0],locality_state_id=int(r[2]),locality_locality_id=int(r[3]),locality_school_id=int(r[4]),locality_ArvTime=d1,locality_quality=int(r[8]))
                tab1.save() 
                cursor.execute("SELECT MAX(locality_MsgID) from SKD_app_locality")
                d2 = cursor.fetchone()
                tab2 = localityTypes(localityTypes_Type=r[5],localityTypes_quantity=int(r[6]),localityTypes_msgId_id=int(d2[0]))               
                tab2.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True 
            elif r[9] == 'Q':  
                d1 = datetime.strptime(r[11],'%Y-%m-%d')
                tab1 = locality(locality_smsType=r[0],locality_state_id=int(r[2]),locality_locality_id=int(r[3]),locality_school_id=int(r[4]),locality_ArvTime=d1,locality_quality=int(r[10]))
                tab1.save() 
                cursor.execute("SELECT MAX(locality_MsgID) from SKD_app_locality")
                d2 = cursor.fetchone()
                tab2 = localityTypes(localityTypes_Type=r[5],localityTypes_quantity=int(r[6]),localityTypes_msgId_id=int(d2[0]))
                tab3 = localityTypes(localityTypes_Type=r[7],localityTypes_quantity=int(r[8]),localityTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[11] == 'Q':  
                d1 = datetime.strptime(r[13],'%Y-%m-%d')
                tab1 = locality(locality_smsType=r[0],locality_state_id=int(r[2]),locality_locality_id=int(r[3]),locality_school_id=int(r[4]),locality_ArvTime=d1,locality_quality=int(r[12])) 
                tab1.save() 
                cursor.execute("SELECT MAX(locality_MsgID) from SKD_app_locality")
                d2 = cursor.fetchone()
                tab2 = localityTypes(localityTypes_Type=r[5],localityTypes_quantity=int(r[6]),localityTypes_msgId_id=int(d2[0]))
                tab3 = localityTypes(localityTypes_Type=r[7],localityTypes_quantity=int(r[8]),localityTypes_msgId_id=int(d2[0]))
                tab4 = localityTypes(localityTypes_Type=r[9],localityTypes_quantity=int(r[10]),localityTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[13] == 'Q':    
                d1 = datetime.strptime(r[15],'%Y-%m-%d')
                tab1 = locality(locality_smsType=r[0],locality_state_id=int(r[2]),locality_locality_id=int(r[3]),locality_school_id=int(r[4])) 
                cursor.execute("SELECT MAX(locality_MsgID) from SKD_app_locality")
                d2 = cursor.fetchone()
                tab2 = localityTypes(localityTypes_Type=r[5],localityTypes_quantity=int(r[6]),localityTypes_msgId_id=int(d2[0]))
                tab3 = localityTypes(localityTypes_Type=r[7],localityTypes_quantity=int(r[8]),localityTypes_msgId_id=int(d2[0]))
                tab4 = localityTypes(localityTypes_Type=r[9],localityTypes_quantity=int(r[10]),localityTypes_msgId_id=int(d2[0]))
                tab5 = localityTypes(localityTypes_Type=r[11],localityTypes_quantity=int(r[12]),localityTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[15] == 'Q':    
                d1 = datetime.strptime(r[17],'%Y-%m-%d')
                tab1 = locality(locality_smsType=r[0],locality_state_id=int(r[2]),locality_locality_id=int(r[3]),locality_school_id=int(r[4]),locality_ArvTime=d1,locality_quality=int(r[16])) 
                tab1.save()
                cursor.execute("SELECT MAX(locality_MsgID) from SKD_app_locality")
                d2 = cursor.fetchone()
                tab2 = localityTypes(localityTypes_Type=r[5],localityTypes_quantity=int(r[6]),localityTypes_msgId_id=int(d2[0]))
                tab3 = localityTypes(localityTypes_Type=r[7],localityTypes_quantity=int(r[8]),localityTypes_msgId_id=int(d2[0]))
                tab4 = localityTypes(localityTypes_Type=r[9],localityTypes_quantity=int(r[10]),localityTypes_msgId_id=int(d2[0]))
                tab5 = localityTypes(localityTypes_Type=r[11],localityTypes_quantity=int(r[12]),localityTypes_msgId_id=int(d2[0]))
                tab6 = localityTypes(localityTypes_Type=r[13],localityTypes_quantity=int(r[14]),localityTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True          
            elif r[17] == 'Q':    
                d1 = datetime.strptime(r[19],'%Y-%m-%d')
                tab1 = locality(locality_smsType=r[0],locality_state_id=int(r[2]),locality_locality_id=int(r[3]),locality_school_id=int(r[4]),locality_ArvTime=d1,locality_quality=int(r[18])) 
                tab1.save()
                cursor.execute("SELECT MAX(locality_MsgID) from SKD_app_locality")
                d2 = cursor.fetchone()
                tab2 = localityTypes(localityTypes_Type=r[5],localityTypes_quantity=int(r[6]),localityTypes_msgId_id=int(d2[0]))
                tab3 = localityTypes(localityTypes_Type=r[7],localityTypes_quantity=int(r[8]),localityTypes_msgId_id=int(d2[0]))
                tab4 = localityTypes(localityTypes_Type=r[9],localityTypes_quantity=int(r[10]),localityTypes_msgId_id=int(d2[0]))
                tab5 = localityTypes(localityTypes_Type=r[11],localityTypes_quantity=int(r[12]),localityTypes_msgId_id=int(d2[0]))
                tab6 = localityTypes(localityTypes_Type=r[13],localityTypes_quantity=int(r[14]),localityTypes_msgId_id=int(d2[0]))
                tab7 = localityTypes(localityTypes_Type=r[15],localityTypes_quantity=int(r[16]),localityTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True   
            elif r[19] == 'Q':    
                d1 = datetime.strptime(r[21],'%Y-%m-%d')
                tab1 = locality(locality_smsType=r[0],locality_state_id=int(r[2]),locality_locality_id=int(r[3]),locality_school_id=int(r[4]),locality_ArvTime=21,locality_quality=int(r[20]))
                tab1.save() 
                cursor.execute("SELECT MAX(locality_MsgID) from SKD_app_locality")
                d2 = cursor.fetchone()
                tab2 = localityTypes(localityTypes_Type=r[5],localityTypes_quantity=int(r[6]),localityTypes_msgId_id=int(d2[0]))
                tab3 = localityTypes(localityTypes_Type=r[7],localityTypes_quantity=int(r[8]),localityTypes_msgId_id=int(d2[0]))
                tab4 = localityTypes(localityTypes_Type=r[9],localityTypes_quantity=int(r[10]),localityTypes_msgId_id=int(d2[0]))
                tab5 = localityTypes(localityTypes_Type=r[11],localityTypes_quantity=int(r[12]),localityTypes_msgId_id=int(d2[0]))
                tab6 = localityTypes(localityTypes_Type=r[13],localityTypes_quantity=int(r[14]),localityTypes_msgId_id=int(d2[0]))
                tab7 = localityTypes(localityTypes_Type=r[15],localityTypes_quantity=int(r[16]),localityTypes_msgId_id=int(d2[0]))
                tab8 = localityTypes(localityTypes_Type=r[17],localityTypes_quantity=int(r[18]),localityTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[21] == 'Q':    
                d1 = datetime.strptime(r[23],'%Y-%m-%d')
                tab1 = locality(locality_smsType=r[0],locality_state_id=int(r[2]),locality_locality_id=int(r[3]),locality_school_id=int(r[4]),locality_ArvTime=d1,locality_quality=int(r[22])) 
                tab1.save()
                cursor.execute("SELECT MAX(locality_MsgID) from SKD_app_locality")
                d2 = cursor.fetchone()
                tab2 = localityTypes(localityTypes_Type=r[5],localityTypes_quantity=int(r[6]),localityTypes_msgId_id=int(d2[0]))
                tab3 = localityTypes(localityTypes_Type=r[7],localityTypes_quantity=int(r[8]),localityTypes_msgId_id=int(d2[0]))
                tab4 = localityTypes(localityTypes_Type=r[9],localityTypes_quantity=int(r[10]),localityTypes_msgId_id=int(d2[0]))
                tab5 = localityTypes(localityTypes_Type=r[11],localityTypes_quantity=int(r[12]),localityTypes_msgId_id=int(d2[0]))
                tab6 = localityTypes(localityTypes_Type=r[13],localityTypes_quantity=int(r[14]),localityTypes_msgId_id=int(d2[0]))
                tab7 = localityTypes(localityTypes_Type=r[15],localityTypes_quantity=int(r[16]),localityTypes_msgId_id=int(d2[0]))
                tab8 = localityTypes(localityTypes_Type=r[17],localityTypes_quantity=int(r[18]),localityTypes_msgId_id=int(d2[0]))
                tab9 = localityTypes(localityTypes_Type=r[19],localityTypes_quantity=int(r[20]),localityTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True        
            elif r[23] == 'Q':    
                d1 = datetime.strptime(r[25],'%Y-%m-%d')
                tab1 = locality(locality_smsType=r[0],locality_state_id=int(r[2]),locality_locality_id=int(r[3]),locality_school_id=int(r[4]),locality_ArvTime=d1,locality_quality=int(r[24])) 
                tab1.save()
                cursor.execute("SELECT MAX(locality_MsgID) from SKD_app_locality")
                d2 = cursor.fetchone()
                tab2 = localityTypes(localityTypes_Type=r[5],localityTypes_quantity=int(r[6]),localityTypes_msgId_id=int(d2[0]))
                tab3 = localityTypes(localityTypes_Type=r[7],localityTypes_quantity=int(r[8]),localityTypes_msgId_id=int(d2[0]))
                tab4 = localityTypes(localityTypes_Type=r[9],localityTypes_quantity=int(r[10]),localityTypes_msgId_id=int(d2[0]))
                tab5 = localityTypes(localityTypes_Type=r[11],localityTypes_quantity=int(r[12]),localityTypes_msgId_id=int(d2[0]))
                tab6 = localityTypes(localityTypes_Type=r[13],localityTypes_quantity=int(r[14]),localityTypes_msgId_id=int(d2[0]))
                tab7 = localityTypes(localityTypes_Type=r[15],localityTypes_quantity=int(r[16]),localityTypes_msgId_id=int(d2[0]))
                tab8 = localityTypes(localityTypes_Type=r[17],localityTypes_quantity=int(r[18]),localityTypes_msgId_id=int(d2[0]))
                tab9 = localityTypes(localityTypes_Type=r[19],localityTypes_quantity=int(r[20]),localityTypes_msgId_id=int(d2[0]))
                tab10 = localityTypes(localityTypes_Type=r[21],localityTypes_quantity=int(r[22]),localityTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True     
            elif r[25] == 'Q':    
                d1 = datetime.strptime(r[27],'%Y-%m-%d')
                tab1 = locality(locality_smsType=r[0],locality_state_id=int(r[2]),locality_locality_id=int(r[3]),locality_school_id=int(r[4]),locality_ArvTime=d1,locality_quality=int(r[26])) 
                tab1.save()
                cursor.execute("SELECT MAX(locality_MsgID) from SKD_app_locality")
                d2 = cursor.fetchone()
                tab2 = localityTypes(localityTypes_Type=r[5],localityTypes_quantity=int(r[6]),localityTypes_msgId_id=int(d2[0]))
                tab3 = localityTypes(localityTypes_Type=r[7],localityTypes_quantity=int(r[8]),localityTypes_msgId_id=int(d2[0]))
                tab4 = localityTypes(localityTypes_Type=r[9],localityTypes_quantity=int(r[10]),localityTypes_msgId_id=int(d2[0]))
                tab5 = localityTypes(localityTypes_Type=r[11],localityTypes_quantity=int(r[12]),localityTypes_msgId_id=int(d2[0]))
                tab6 = localityTypes(localityTypes_Type=r[13],localityTypes_quantity=int(r[14]),localityTypes_msgId_id=int(d2[0]))
                tab7 = localityTypes(localityTypes_Type=r[15],localityTypes_quantity=int(r[16]),localityTypes_msgId_id=int(d2[0]))
                tab8 = localityTypes(localityTypes_Type=r[17],localityTypes_quantity=int(r[18]),localityTypes_msgId_id=int(d2[0]))
                tab9 = localityTypes(localityTypes_Type=r[19],localityTypes_quantity=int(r[20]),localityTypes_msgId_id=int(d2[0]))
                tab10 = localityTypes(localityTypes_Type=r[21],localityTypes_quantity=int(r[22]),localityTypes_msgId_id=int(d2[0]))
                tab11 = localityTypes(localityTypes_Type=r[23],localityTypes_quantity=int(r[24]),localityTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                tab11.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True    
            elif r[27] == 'Q':    
                d1 = datetime.strptime(r[29],'%Y-%m-%d')
                tab1 = locality(locality_smsType=r[0],locality_state_id=int(r[2]),locality_locality_id=int(r[3]),locality_school_id=int(r[4]),locality_ArvTime=d1,locality_quality=int(r[28])) 
                tab1.save()
                cursor.execute("SELECT MAX(locality_MsgID) from SKD_app_locality")
                d2 = cursor.fetchone()
                tab2 = localityTypes(localityTypes_Type=r[5],localityTypes_quantity=int(r[6]),localityTypes_msgId_id=int(d2[0]))
                tab3 = localityTypes(localityTypes_Type=r[7],localityTypes_quantity=int(r[8]),localityTypes_msgId_id=int(d2[0]))
                tab4 = localityTypes(localityTypes_Type=r[9],localityTypes_quantity=int(r[10]),localityTypes_msgId_id=int(d2[0]))
                tab5 = localityTypes(localityTypes_Type=r[11],localityTypes_quantity=int(r[12]),localityTypes_msgId_id=int(d2[0]))
                tab6 = localityTypes(localityTypes_Type=r[13],localityTypes_quantity=int(r[14]),localityTypes_msgId_id=int(d2[0]))
                tab7 = localityTypes(localityTypes_Type=r[15],localityTypes_quantity=int(r[16]),localityTypes_msgId_id=int(d2[0]))
                tab8 = localityTypes(localityTypes_Type=r[17],localityTypes_quantity=int(r[18]),localityTypes_msgId_id=int(d2[0]))
                tab9 = localityTypes(localityTypes_Type=r[19],localityTypes_quantity=int(r[20]),localityTypes_msgId_id=int(d2[0]))
                tab10 = localityTypes(localityTypes_Type=r[21],localityTypes_quantity=int(r[22]),localityTypes_msgId_id=int(d2[0]))
                tab11 = localityTypes(localityTypes_Type=r[23],localityTypes_quantity=int(r[24]),localityTypes_msgId_id=int(d2[0]))
                tab12 = localityTypes(localityTypes_Type=r[25],localityTypes_quantity=int(r[26]),localityTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                tab11.save()   
                tab12.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True     
            elif r[29] == 'Q':    
                d1 = datetime.strptime(r[31],'%Y-%m-%d')
                tab1 = locality(locality_smsType=r[0],locality_state_id=int(r[2]),locality_locality_id=int(r[3]),locality_school_id=int(r[4]),locality_ArvTime=d1,locality_quality=int(r[30])) 
                tab1.save()
                cursor.execute("SELECT MAX(locality_MsgID) from SKD_app_locality")
                d2 = cursor.fetchone()
                tab2 = localityTypes(localityTypes_Type=r[5],localityTypes_quantity=int(r[6]),localityTypes_msgId_id=int(d2[0]))
                tab3 = localityTypes(localityTypes_Type=r[7],localityTypes_quantity=int(r[8]),localityTypes_msgId_id=int(d2[0]))
                tab4 = localityTypes(localityTypes_Type=r[9],localityTypes_quantity=int(r[10]),localityTypes_msgId_id=int(d2[0]))
                tab5 = localityTypes(localityTypes_Type=r[11],localityTypes_quantity=int(r[12]),localityTypes_msgId_id=int(d2[0]))
                tab6 = localityTypes(localityTypes_Type=r[13],localityTypes_quantity=int(r[14]),localityTypes_msgId_id=int(d2[0]))
                tab7 = localityTypes(localityTypes_Type=r[15],localityTypes_quantity=int(r[16]),localityTypes_msgId_id=int(d2[0]))
                tab8 = localityTypes(localityTypes_Type=r[17],localityTypes_quantity=int(r[18]),localityTypes_msgId_id=int(d2[0]))
                tab9 = localityTypes(localityTypes_Type=r[19],localityTypes_quantity=int(r[20]),localityTypes_msgId_id=int(d2[0]))
                tab10 = localityTypes(localityTypes_Type=r[21],localityTypes_quantity=int(r[22]),localityTypes_msgId_id=int(d2[0]))
                tab11 = localityTypes(localityTypes_Type=r[23],localityTypes_quantity=int(r[24]),localityTypes_msgId_id=int(d2[0]))
                tab12 = localityTypes(localityTypes_Type=r[25],localityTypes_quantity=int(r[26]),localityTypes_msgId_id=int(d2[0]))
                tab13 = localityTypes(localityTypes_Type=r[27],localityTypes_quantity=int(r[28]),localityTypes_msgId_id=int(d2[0]))               
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                tab11.save()   
                tab12.save()
                tab13.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True       
        elif r[1] == 'S':     
            if r[6] == 'Q':
                d1 = datetime.strptime(r[8],'%Y-%m-%d')
                tab1 = school(school_smsType=r[0],school_locality_id=int(r[2]),school_school_id=int(r[3]),school_ArvTime=d1,school_quality=int(r[7]))
                tab1.save() 
                cursor.execute("SELECT MAX(school_MsgID) from SKD_app_school")
                d2 = cursor.fetchone()
                tab2 = schoolTypes(schoolTypes_Type=r[4],schoolTypes_quantity=int(r[5]),schoolTypes_msgId_id=int(d2[0]))
                tab1.save()               
                tab2.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True 
            elif r[8] == 'Q':  
                d1 = datetime.strptime(r[10],'%Y-%m-%d')
                tab1 = school(school_smsType=r[0],school_locality_id=int(r[2]),school_school_id=int(r[3]),school_ArvTime=d1,school_quality=int(r[9])) 
                tab1.save()
                cursor.execute("SELECT MAX(school_MsgID) from SKD_app_school")
                d2 = cursor.fetchone()
                tab2 = schoolTypes(schoolTypes_Type=r[4],schoolTypes_quantity=int(r[5]),schoolTypes_msgId_id=int(d2[0]))
                tab3 = schoolTypes(schoolTypes_Type=r[6],schoolTypes_quantity=int(r[7]),schoolTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[10] == 'Q':  
                d1 = datetime.strptime(r[12],'%Y-%m-%d')
                tab1 = school(school_smsType=r[0],school_locality_id=int(r[2]),school_school_id=int(r[3]),school_ArvTime=d1,school_quality=int(r[11])) 
                tab1.save()
                cursor.execute("SELECT MAX(school_MsgID) from SKD_app_school")
                d2 = cursor.fetchone()
                tab2 = schoolTypes(schoolTypes_Type=r[4],schoolTypes_quantity=int(r[5]),schoolTypes_msgId_id=int(d2[0]))
                tab3 = schoolTypes(schoolTypes_Type=r[6],schoolTypes_quantity=int(r[7]),schoolTypes_msgId_id=int(d2[0]))
                tab4 = schoolTypes(schoolTypes_Type=r[8],schoolTypes_quantity=int(r[9]),schoolTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[12] == 'Q':    
                d1 = datetime.strptime(r[14],'%Y-%m-%d')
                tab1 = school(school_smsType=r[0],school_locality_id=int(r[2]),school_school_id=int(r[3]),school_ArvTime=d1,school_quality=int(r[13])) 
                tab1.save()
                cursor.execute("SELECT MAX(school_MsgID) from SKD_app_school")
                d2 = cursor.fetchone()
                tab2 = schoolTypes(schoolTypes_Type=r[4],schoolTypes_quantity=int(r[5]),schoolTypes_msgId_id=int(d2[0]))
                tab3 = schoolTypes(schoolTypes_Type=r[6],schoolTypes_quantity=int(r[7]),schoolTypes_msgId_id=int(d2[0]))
                tab4 = schoolTypes(schoolTypes_Type=r[8],schoolTypes_quantity=int(r[9]),schoolTypes_msgId_id=int(d2[0]))
                tab5 = schoolTypes(schoolTypes_Type=r[19],schoolTypes_quantity=int(r[11]),schoolTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True
            elif r[14] == 'Q':    
                d1 = datetime.strptime(r[16],'%Y-%m-%d')
                tab1 = school(school_smsType=r[0],school_locality_id=int(r[2]),school_school_id=int(r[3]),school_ArvTime=d1,school_quality=int(r[15])) 
                tab1.save()
                cursor.execute("SELECT MAX(school_MsgID) from SKD_app_school")
                d2 = cursor.fetchone()
                tab2 = schoolTypes(schoolTypes_Type=r[4],schoolTypes_quantity=int(r[5]),schoolTypes_msgId_id=int(d2[0]))
                tab3 = schoolTypes(schoolTypes_Type=r[6],schoolTypes_quantity=int(r[7]),schoolTypes_msgId_id=int(d2[0]))
                tab4 = schoolTypes(schoolTypes_Type=r[8],schoolTypes_quantity=int(r[9]),schoolTypes_msgId_id=int(d2[0]))
                tab5 = schoolTypes(schoolTypes_Type=r[10],schoolTypes_quantity=int(r[11]),schoolTypes_msgId_id=int(d2[0]))
                tab6 = schoolTypes(schoolTypes_Type=r[12],schoolTypes_quantity=int(r[13]),schoolTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True         
            elif r[16] == 'Q':    
                d1 = datetime.strptime(r[18],'%Y-%m-%d')
                tab1 = school(school_smsType=r[0],school_locality_id=int(r[2]),school_school_id=int(r[3]),school_ArvTime=d1,school_quality=int(r[17])) 
                tab1.save()
                cursor.execute("SELECT MAX(school_MsgID) from SKD_app_school")
                d2 = cursor.fetchone()
                tab2 = schoolTypes(schoolTypes_Type=r[4],schoolTypes_quantity=int(r[5]),schoolTypes_msgId_id=int(d2[0]))
                tab3 = schoolTypes(schoolTypes_Type=r[6],schoolTypes_quantity=int(r[7]),schoolTypes_msgId_id=int(d2[0]))
                tab4 = schoolTypes(schoolTypes_Type=r[8],schoolTypes_quantity=int(r[9]),schoolTypes_msgId_id=int(d2[0]))
                tab5 = schoolTypes(schoolTypes_Type=r[10],schoolTypes_quantity=int(r[11]),schoolTypes_msgId_id=int(d2[0]))
                tab6 = schoolTypes(schoolTypes_Type=r[12],schoolTypes_quantity=int(r[13]),schoolTypes_msgId_id=int(d2[0]))
                tab7 = schoolTypes(schoolTypes_Type=r[14],schoolTypes_quantity=int(r[15]),schoolTypes_msgId_id=int(d2[0]))               
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True   
            elif r[18] == 'Q':    
                d1 = datetime.strptime(r[20],'%Y-%m-%d')
                tab1 = school(school_smsType=r[0],school_locality_id=int(r[2]),school_school_id=int(r[3]),school_ArvTime=d1,school_quality=int(r[19])) 
                tab1.save()
                cursor.execute("SELECT MAX(school_MsgID) from SKD_app_school")
                d2 = cursor.fetchone()
                tab2 = schoolTypes(schoolTypes_Type=r[4],schoolTypes_quantity=int(r[5]),schoolTypes_msgId_id=int(d2[0]))
                tab3 = schoolTypes(schoolTypes_Type=r[6],schoolTypes_quantity=int(r[7]),schoolTypes_msgId_id=int(d2[0]))
                tab4 = schoolTypes(schoolTypes_Type=r[8],schoolTypes_quantity=int(r[9]),schoolTypes_msgId_id=int(d2[0]))
                tab5 = schoolTypes(schoolTypes_Type=r[10],schoolTypes_quantity=int(r[11]),schoolTypes_msgId_id=int(d2[0]))
                tab6 = schoolTypes(schoolTypes_Type=r[12],schoolTypes_quantity=int(r[13]),schoolTypes_msgId_id=int(d2[0]))
                tab7 = schoolTypes(schoolTypes_Type=r[14],schoolTypes_quantity=int(r[15]),schoolTypes_msgId_id=int(d2[0]))
                tab8 = schoolTypes(schoolTypes_Type=r[16],schoolTypes_quantity=int(r[17]),schoolTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True 
            elif r[20] == 'Q':    
                d1 = datetime.strptime(r[22],'%Y-%m-%d')
                tab1 = school(school_smsType=r[0],school_locality_id=int(r[2]),school_school_id=int(r[3]),school_ArvTime=d1,school_quality=int(r[21]))
                tab1.save()
                cursor.execute("SELECT MAX(school_MsgID) from SKD_app_school")
                d2 = cursor.fetchone() 
                tab2 = schoolTypes(schoolTypes_Type=r[4],schoolTypes_quantity=int(r[5]),schoolTypes_msgId_id=int(d2[0]))
                tab3 = schoolTypes(schoolTypes_Type=r[6],schoolTypes_quantity=int(r[7]),schoolTypes_msgId_id=int(d2[0]))
                tab4 = schoolTypes(schoolTypes_Type=r[8],schoolTypes_quantity=int(r[9]),schoolTypes_msgId_id=int(d2[0]))
                tab5 = schoolTypes(schoolTypes_Type=r[10],schoolTypes_quantity=int(r[11]),schoolTypes_msgId_id=int(d2[0]))
                tab6 = schoolTypes(schoolTypes_Type=r[12],schoolTypes_quantity=int(r[13]),schoolTypes_msgId_id=int(d2[0]))
                tab7 = schoolTypes(schoolTypes_Type=r[14],schoolTypes_quantity=int(r[15]),schoolTypes_msgId_id=int(d2[0]))
                tab8 = schoolTypes(schoolTypes_Type=r[16],schoolTypes_quantity=int(r[17]),schoolTypes_msgId_id=int(d2[0]))
                tab9 = schoolTypes(schoolTypes_Type=r[18],schoolTypes_quantity=int(r[19]),schoolTypes_msgId_id=int(d2[0]))               
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True         
            elif r[22] == 'Q':    
                d1 = datetime.strptime(r[24],'%Y-%m-%d')
                tab1 = school(school_smsType=r[0],school_locality_id=int(r[2]),school_school_id=int(r[3]),school_ArvTime=d1,school_quality=int(r[23])) 
                tab1.save()
                cursor.execute("SELECT MAX(school_MsgID) from SKD_app_school")
                d2 = cursor.fetchone()
                tab2 = schoolTypes(schoolTypes_Type=r[4],schoolTypes_quantity=int(r[5]),schoolTypes_msgId_id=int(d2[0]))
                tab3 = schoolTypes(schoolTypes_Type=r[6],schoolTypes_quantity=int(r[7]),schoolTypes_msgId_id=int(d2[0]))
                tab4 = schoolTypes(schoolTypes_Type=r[8],schoolTypes_quantity=int(r[9]),schoolTypes_msgId_id=int(d2[0]))
                tab5 = schoolTypes(schoolTypes_Type=r[10],schoolTypes_quantity=int(r[11]),schoolTypes_msgId_id=int(d2[0]))
                tab6 = schoolTypes(schoolTypes_Type=r[12],schoolTypes_quantity=int(r[13]),schoolTypes_msgId_id=int(d2[0]))
                tab7 = schoolTypes(schoolTypes_Type=r[14],schoolTypes_quantity=int(r[15]),schoolTypes_msgId_id=int(d2[0]))
                tab8 = schoolTypes(schoolTypes_Type=r[16],schoolTypes_quantity=int(r[17]),schoolTypes_msgId_id=int(d2[0]))
                tab9 = schoolTypes(schoolTypes_Type=r[18],schoolTypes_quantity=int(r[19]),schoolTypes_msgId_id=int(d2[0]))
                tab10 = schoolTypes(schoolTypes_Type=r[20],schoolTypes_quantity=int(r[21]),schoolTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()  
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True   
            elif r[24] == 'Q':    
                d1 = datetime.strptime(r[26],'%Y-%m-%d')
                tab1 = school(school_smsType=r[0],school_locality_id=int(r[2]),school_school_id=int(r[3]),school_ArvTime=d1,school_quality=int(r[25])) 
                tab1.save()
                cursor.execute("SELECT MAX(school_MsgID) from SKD_app_school")
                d2 = cursor.fetchone()
                tab2 = schoolTypes(schoolTypes_Type=r[4],schoolTypes_quantity=int(r[5]),schoolTypes_msgId_id=int(d2[0]))
                tab3 = schoolTypes(schoolTypes_Type=r[6],schoolTypes_quantity=int(r[7]),schoolTypes_msgId_id=int(d2[0]))
                tab4 = schoolTypes(schoolTypes_Type=r[8],schoolTypes_quantity=int(r[9]),schoolTypes_msgId_id=int(d2[0]))
                tab5 = schoolTypes(schoolTypes_Type=r[10],schoolTypes_quantity=int(r[11]),schoolTypes_msgId_id=int(d2[0]))
                tab6 = schoolTypes(schoolTypes_Type=r[12],schoolTypes_quantity=int(r[13]),schoolTypes_msgId_id=int(d2[0]))
                tab7 = schoolTypes(schoolTypes_Type=r[14],schoolTypes_quantity=int(r[15]),schoolTypes_msgId_id=int(d2[0]))
                tab8 = schoolTypes(schoolTypes_Type=r[16],schoolTypes_quantity=int(r[17]),schoolTypes_msgId_id=int(d2[0]))
                tab9 = schoolTypes(schoolTypes_Type=r[18],schoolTypes_quantity=int(r[19]),schoolTypes_msgId_id=int(d2[0]))
                tab10 = schoolTypes(schoolTypes_Type=r[20],schoolTypes_quantity=int(r[21]),schoolTypes_msgId_id=int(d2[0]))
                tab11 = schoolTypes(schoolTypes_Type=r[22],schoolTypes_quantity=int(r[23]),schoolTypes_msgId_id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                tab11.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True    
            elif r[26] == 'Q':    
                d1 = datetime.strptime(r[28],'%Y-%m-%d')
                tab1 = school(school_smsType=r[0],school_locality_id=int(r[2]),school_school_id=int(r[3]),school_ArvTime=d1,school_quality=int(r[27])) 
                tab1.save()
                cursor.execute("SELECT MAX(school_MsgID) from SKD_app_school")
                d2 = cursor.fetchone()
                tab2 = schoolTypes(schoolTypes_Type=r[4],schoolTypes_quantity=int(r[5]),schoolTypes_msgId_id=int(d2[0]))
                tab3 = schoolTypes(schoolTypes_Type=r[6],schoolTypes_quantity=int(r[7]),schoolTypes_msgId_id=int(d2[0]))
                tab4 = schoolTypes(schoolTypes_Type=r[8],schoolTypes_quantity=int(r[9]),schoolTypes_msgId_id=int(d2[0]))
                tab5 = schoolTypes(schoolTypes_Type=r[10],schoolTypes_quantity=int(r[11]),schoolTypes_msgId_id=int(d2[0]))
                tab6 = schoolTypes(schoolTypes_Type=r[12],schoolTypes_quantity=int(r[13]),schoolTypes_msgId_id=int(d2[0]))
                tab7 = schoolTypes(schoolTypes_Type=r[14],schoolTypes_quantity=int(r[15]),schoolTypes_msgId_id=int(d2[0]))
                tab8 = schoolTypes(schoolTypes_Type=r[16],schoolTypes_quantity=int(r[17]),schoolTypes_msgId_id=int(d2[0]))
                tab9 = schoolTypes(schoolTypes_Type=r[18],schoolTypes_quantity=int(r[19]),schoolTypes_msgId_id=int(d2[0]))
                tab10 = schoolTypes(schoolTypes_Type=r[20],schoolTypes_quantity=int(r[21]),schoolTypes_msgId_id=int(d2[0]))
                tab11 = schoolTypes(schoolTypes_Type=r[22],schoolTypes_quantity=int(r[23]),schoolTypes_msgId_id=int(d2[0]))
                tab12 = schoolTypes(schoolTypes_Type=r[24],schoolTypes_quantity=int(r[25]),schoolTypes__id=int(d2[0]))                
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                tab11.save()   
                tab12.save() 
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True     
            elif r[28] == 'Q':    
                d1 = datetime.strptime(r[30],'%Y-%m-%d')
                tab1 = school(school_smsType=r[0],school_locality_id=int(r[2]),school_school_id=int(r[3]),school_ArvTime=d1,school_quality=int(r[29]))
                tab1.save()
                cursor.execute("SELECT MAX(school_MsgID) from SKD_app_school")
                d2 = cursor.fetchone() 
                tab2 = schoolTypes(schoolTypes_Type=r[4],schoolTypes_quantity=int(r[5]),schoolTypes_msgId_id=int(d2[0]))
                tab3 = schoolTypes(schoolTypes_Type=r[6],schoolTypes_quantity=int(r[7]),schoolTypes_msgId_id=int(d2[0]))
                tab4 = schoolTypes(schoolTypes_Type=r[8],schoolTypes_quantity=int(r[9]),schoolTypes_msgId_id=int(d2[0]))
                tab5 = schoolTypes(schoolTypes_Type=r[10],schoolTypes_quantity=int(r[11]),schoolTypes_msgId_id=int(d2[0]))
                tab6 = schoolTypes(schoolTypes_Type=r[12],schoolTypes_quantity=int(r[13]),schoolTypes_msgId_id=int(d2[0]))
                tab7 = schoolTypes(schoolTypes_Type=r[14],schoolTypes_quantity=int(r[15]),schoolTypes_msgId_id=int(d2[0]))
                tab8 = schoolTypes(schoolTypes_Type=r[16],schoolTypes_quantity=int(r[17]),schoolTypes_msgId_id=int(d2[0]))
                tab9 = schoolTypes(schoolTypes_Type=r[18],schoolTypes_quantity=int(r[19]),schoolTypes_msgId_id=int(d2[0]))
                tab10 = schoolTypes(schoolTypes_Type=r[20],schoolTypes_quantity=int(r[21]),schoolTypes_msgId_id=int(d2[0]))
                tab11 = schoolTypes(schoolTypes_Type=r[22],schoolTypes_quantity=int(r[23]),schoolTypes_msgId_id=int(d2[0]))
                tab12 = schoolTypes(schoolTypes_Type=r[24],schoolTypes_quantity=int(r[25]),schoolTypes_msgId_id=int(d2[0]))
                tab13 = schoolTypes(schoolTypes_Type=r[26],schoolTypes_quantity=int(r[27]),schoolTypes_msgId_id=int(d2[0]))              
                tab2.save()
                tab3.save()
                tab4.save()
                tab5.save()
                tab6.save() 
                tab7.save()
                tab8.save()  
                tab9.save() 
                tab10.save()
                tab11.save()   
                tab12.save()
                tab13.save()
                response = "Your Message was recieved successfully"
                self.debug("responding with %s", response)
                message.respond(response)
                cursor.close ()
                db1.close ()
                return True      
        else:       
            response = "wrong message!! "
            self.debug("responding with %s", response)
            message.respond(response)
            return True
            
    def cleanup (self, message):
            """Perform any clean up after all handlers have run in the
            cleanup phase."""
            pass

    def outgoing (self, message):
        """Handle outgoing message notifications."""
        pass

    def stop (self):
        """Perform global app cleanup when the application is stopped."""
        pass        

